### ISSUE TITLE
Issue while trying to unit test

### ISSUE THREAD

**Issue by nightfall708** [marcuseckert/Squall#1]
Hi there,

We're experiencing this error:

fatal error: lipo: Input file: /Users/user/Library/Developer/Xcode/DerivedData/myapp-gnirtfppnojyrcabedzwrszivhfw/Build/Products/Debug-iphonesimulator/MyApp.app/Frameworks/Squall.framework/Squall changed since opened (Undefined error: 0)

(integration was made with coocapods)

**Comment by marcuseckert** [comment]
So I've now also set up a project with a Unit test target and it runs fine for me so it's now hard to say what's causing it on your end. 
Are you changing the framework in some way? Stripping architecture slices, for example? Otherwise it's likely the cocoapods integration is messing with it. Have you tried it with the use_frameworks! flag or without it in the podfile? Another thing you might try is setting up a new, clean project and try to run it there, might give you an indication if it's related to your project settings.

**Comment by nightfall708** [comment]
are you using Cocoapods 1.0 ?

**Comment by marcuseckert** [comment]
Yes

**Comment by nightfall708** [comment]
Well I eventually added the framework statically (vs pod) and it stopped giving me this error.

**Comment by nightfall708** [comment]
Trying to get back to the pod configuration. This is a more detailed error:

fatal error: lipo: -remove arm64 specified but fat file: /Users/user/Library/Developer/Xcode/DerivedData/myapp-gnirtfppnojyrcabedzwrszivhfw/Build/Products/Debug-iphonesimulator/MyApp.app/Frameworks/Squall.framework/Squall does not contain that architecture

**Comment by marcuseckert** [comment]
Have you tried integrating it in a new, clean project? The framework does contain arm64 but you can check by running by going into the Squall.framework folder and running file on Squall. It should print the following:
Squall: Mach-O universal binary with 5 architectures
Squall (for architecture x86_64):   Mach-O 64-bit dynamically linked shared library x86_64
Squall (for architecture i386): Mach-O dynamically linked shared library i386
Squall (for architecture armv7):    Mach-O dynamically linked shared library arm
Squall (for architecture armv7s):   Mach-O dynamically linked shared library arm
Squall (for architecture arm64):    Mach-O 64-bit dynamically linked shared library

**Comment by nightfall708** [comment]
Looks like deleting derived data fixed it. Hopefully it doesn't break! Thanks

**Comment by nightfall708** [comment]
Seems that after one more build the error comes back. The builds are also failing on buddybuild.com. 
I opened a ticket so I'm reopening the ticket here too for now.

**Comment by marcuseckert** [comment]
So have you tried integrating it in a clean, new project with cocoapods?

**Comment by nightfall708** [comment]
Haven't done that yet I'm guessing it'll work.

**Comment by aymericio** [comment]
I get a similar error when I try to run my unit tests, after adding `@testable import MyApp`

```
ld: framework not found Squall for architecture x86_64
```

**Comment by marcuseckert** [comment]
Without having been able to reproduce it, here's an educated guess: I guess you're integrating with Cocoapods and it's stripping away the sim architectures when building. 
In the build phases of your target it should have a phase called "Embed Pods Frameworks" and there it should provide a path to a .sh file. 
In that file there is a passage where it says "Strip invalid architectures". Try commenting that out (this might break other things and will most definitely break submitting to the app store). You could also set this part into an if clause and only run it if the target configuration is debug or whatever you're using for testing. 
hope that gets you on your way.

**Comment by aymericio** [comment]
I get the problem since than I implemented [Realm](realm.io). Indeed, I used Cocoapods to install Squall but Squall is not presents in my `AppTests` target.

**Comment by marcuseckert** [comment]
But I think it might be via the Cocoapods integration. I don't use Cocoapods that often but have you tried the above mentioned approach?

**Comment by aymericio** [comment]
I tried to disable `strip_invalid_archs()` but I get always the error.

**Comment by aymericio** [comment]
All my apologies @marcuseckert! My problem come from `@testable import MyApp` and my pods

**Comment by aymericio** [comment]
I removed Squall from Podfile and I installed it manually. It works but I still can't run unit tests and I get always the same error:

```
ld: framework not found Squall for architecture x86_64
```

Can you fix that please?

**Comment by marcuseckert** [comment]
Not sure how.
Did you not say you resolved this?
Chances are there is sth broken in your setup. The framework does contain slices for x86_64. My guess is sth in your setup is probably stripping it along the way.

**Comment by marcuseckert** [comment]
You could also try to link the squall.framework binary directly with your test target (as opposed to the target the test is for)

**Comment by aymericio** [comment]
Hum that works by adding Squall in test target. That never worked with cocoapods.
