### ISSUE TITLE
version 2.0.0 is so fat!!!

### ISSUE THREAD

**Issue by xushao1990** [marcuseckert/Squall#11]
Nearly 100 M！！！
some way to reduce?
I have to use version 1.22。
/(ㄒoㄒ)/~~

**Comment by marcuseckert** [comment]
Hey, if you're concerned about your app bundle size, most of this will get stripped before it lands in the app store and optimized via bitcode. The Squall companion app which uses the SDK is only 6.7 MB, so it won't contribute much to the overall bundle size. 
If for some other reason you need it to be smaller, you could strip unwanted architectures. This script would strip the simulator slices: https://github.com/realm/realm-cocoa/blob/d59c86f11525f346c8e8db277fdbf2d9ff990d98/scripts/strip-frameworks.sh
But obviously, then you won't be able to run it on the simulator. 
Hope this helps.
