### ISSUE TITLE
Adaptive Transition Issues

### ISSUE THREAD

**Issue by streamside7** [marcuseckert/Squall#12]
The Adaptive Transition example does not perform on an iPhone 6 the way it is depicted in the animated GIF. I am using the trial version.

In short, the animation does not finish before the scene abruptly is replaced by the new view.

This is a critical requirement for purchase. If I can be of any help in troubleshooting this issue, please let me know.

**Comment by marcuseckert** [comment]
the trial SDK has a 1s preview limit so this particular example won't work with an unlicensed copy:/

**Comment by streamside7** [comment]
@marcuseckert is there a way to either extend the trial preview limit or create a shorter transition that will prove how well it works? I appreciate that piracy is rampant, believe me, but the fact that your example isn't testable within the preview limit makes the trial less useful.

**Comment by marcuseckert** [comment]
Yeah, the trial is of limited functionality for testing the SDK, that's true, but so far I haven't come up with a better way to handle it without implementing some Orwellian licensing solution or spending more time on locking it down than making it better. Sorry:/
But you can look at the code, trim down the sample (or use your own AE file) and try to rig up your own transition within the time constraints. 
In general, transitions are advanced usage and may require quite some trial and error to get right.
