### ISSUE TITLE
AdaptiveTransition with xcode 8.2.1 simulator doesn't match example gif

### ISSUE THREAD

**Issue by joel-petersen** [marcuseckert/Squall#13]
It seems to get clipped at the very beginning during the transitions.

**Comment by marcuseckert** [comment]
you need to supply a valid license, otherwise animations are clipped at 1s:/

**Comment by joel-petersen** [comment]
Ah, yeah I did read that in the documentation, but for some reason I didnt think that would apply to the example project. 

One idea to reduce the confusion, it might help if the shortening were part of this README, or referenced that there is a change of behavior based on the missing license and have that link to the place in documentation (so you dont have to update it in 2 places if you change the restriction).

Anyway I'm doing a tech evaluation and it is going to make it difficult for me to do a profiling evaluation for our min spec device (iphone5) in its current state. I'd suggest an alternate solution where you injected a pink overlay or something of that nature, so it wouldnt produce shippable results, but still behave mostly correct. I'm guessing the reason you didnt go down that path would be people writing code to just remove the pink view or some other hacks like that.
 
Anyway I'll close the ticket. Thanks and overall the package looks great (from a feature perspective).
