### ISSUE TITLE
Spinner demo , Animation stops after few seconds. kindly do suggestions.

### ISSUE THREAD

**Issue by alpesh12** [marcuseckert/Squall#15]
Repetition of  animation , we are facing issue like below.  we are using ios 10.2 simulator and step 1) added purchased key to run demo 2) animation start and stop after few seconds. ..rest of think as per your given libs..so what is your suggestion kindly help us .

**Comment by marcuseckert** [comment]
Hey,
yes, you caught a bug, I'll fix it in the next update but here's what you can do in the meantime:
1. the function signature in the app delegate where it sets the licence has changed, it is now:
`func applicationDidFinishLaunching(_ application: UIApplication) { `
So you can change that signature or just set the license somewhere else, just make sure to actually set the license. 
2. After that Squall will still stop the animation when the original AE composition reached the end. Right now you need to open the spinner.aep file, make the composition longer (however long you want the spinner to spin) and save the new composition to the spinner.sqa file. 
In the next version I'll add an option for it to ignore the composition duration.
This should solve it for the time being.
