### ISSUE TITLE
Accelerometer example do nothing

### ISSUE THREAD

**Issue by AndrewiOS** [marcuseckert/Squall#16]
Hi guys! Just tried to figure out your example, started it on iPhone 7 iOS 10.3.2 via Xcode 8.3.3 and getwhite screen and 

2017-07-17 18:24:14.424375+0300 Accelerometer[1663:947247] Unknown class _TtC13Accelerometer14ViewController in Interface Builder file.

in the console. What I did wrong?

**Comment by marcuseckert** [comment]
Hey Andrew, 
there's a bug in the example, I'll fix it!

**Comment by AndrewiOS** [comment]
Thank you, Marcus

**Comment by marcuseckert** [comment]
Hey Andrew, I pushed the changes sooner than expected. I haven't been able to replicate your exact problem but some other stuff was broken as well and it's now working again on my end. 
Try pulling the new version and let me know if you're still having problems!

**Comment by AndrewiOS** [comment]
Yes, Accelerometer now works but there is a problem with another example AdaptiveTransition

**Comment by marcuseckert** [comment]
What's not working? For this example you need to enter a license since it's longer than 1s
