### ISSUE TITLE
For version 2.46, the bitcode is not supported.

### ISSUE THREAD

**Issue by huibin1984** [marcuseckert/Squall#18]
I setup the squall by cocoaPod. I notice that the bitcode is not supported.

**Comment by marcuseckert** [comment]
If it‘s really urgent you can download the SDK from the website, I‘ll fix the cocoapods integration as soon as possible. Sorry about that:/

**Comment by marcuseckert** [comment]
hey @huibin1984 I just checked and the library does include bitcode. What specifically is not working?

**Comment by finngaida** [comment]
I have this problem, too. It works fine in a development environment, but during Archive Linking I get an error 
```
ld: bitcode bundle could not be generated because 
'/Users/bla/project/Pods/Squall/Squall.framework/Squall' 
was built without full bitcode. All frameworks and dylibs 
for bitcode must be generated from Xcode Archive or 
Install build for architecture armv7
```

And again for `arm64`.

Have yet to test with an older version.

**Comment by marcuseckert** [comment]
Ah, ok, that's weird. But I can reproduce it now. Will look into it!

**Comment by marcuseckert** [comment]
@huibin1984 @finngaida Sorry guys, I found the issue and fixed it. It'll be resolved in the next version. In the meantime here is a pre-release version of the upcoming build:
https://www.dropbox.com/sh/m874172bbahsdqk/AAA2dPGdg2Zfu7oIHUQ9vEFPa?dl=0 
I checked and it now compiles for me. Let me know if you're still having issues!

**Comment by finngaida** [comment]
Perfect, thanks for the quick support!

**Comment by finngaida** [comment]
When will the next version be released?

**Comment by marcuseckert** [comment]
The next version will be somewhat bigger and I don't know when I'll get to it. 
What are you missing? Anything I can help you with in the meantime?

**Comment by huibin1984** [comment]
Thanks.

**Comment by finngaida** [comment]
Ah just want to keep my dependencies consistently in Cocoapods.

**Comment by marcuseckert** [comment]
Hey @finngaida. Sorry for letting you wait this long, I've decided to push a bug fix update to address this (among other things). So you can pull the latest version and it should be working now!
