### ISSUE TITLE
Does not compile on case sensitive file systems

### ISSUE THREAD

**Issue by georgenavarro** [marcuseckert/Squall#19]
The import of UIKit in [SLAnimation.h](https://github.com/marcuseckert/Squall/blob/7813d4a92b4244eb40aa419d0f657462c539b104/Squall.framework/Headers/SLAnimation.h#L10) has the wrong letter casing. It is `#import <UIKit/UiKit.h>` instead of `#import <UIKit/UIKit.h>` so the header cannot be found on case sensitive file systems.

**Comment by marcuseckert** [comment]
Thanks for pointing that out! I've just fixed it and pushed an update (2.46).
