### ISSUE TITLE
App Store will not accept framework

### ISSUE THREAD

**Issue by nightfall708** [marcuseckert/Squall#2]
I'm receiving this error when uploading to the App Store:

ERROR ITMS-90087: "Unsupported Architectures. The executable for MyApp.app/Frameworks/Squall.framework contains unsupported architectures '[x86_64, i386]'."
ERROR ITMS-90087: "Unsupported Architectures. The executable for MyApp.app/Frameworks/Squall.framework contains unsupported architectures '[x86_64, i386]'."

**Comment by marcuseckert** [comment]
Did you integrate with cocoapods? If not, you'll need to strip the simulator architectures: 
http://www.marcuseckert.com/squall/documentation/SDK

**Comment by nightfall708** [comment]
Thanks!

**Comment by nightfall708** [comment]
I've added the post-action shell script (/bin/sh) from the website and selected "provide build settings from" my target. Archived and uploaded. Still rejected because of the same problem :-(

**Comment by marcuseckert** [comment]
It's somewhat frustrating to try to help if you never answer any questions. Did you integrate with cocoapods? While building the archive - is it displaying any error messages relating to the stripping? 
Also, is the framework in the framework folder of your project? If not, it won't work. On success it should print "stripped" and then the architecture. If it doesn't say that, check that the paths in the script are correct.

**Comment by nightfall708** [comment]
OK I moved the script to the 'build phases' from the scheme post-build. Seems to work.
