### ISSUE TITLE
Missing release 1.13 on GitHub + Cocopods

### ISSUE THREAD

**Issue by aymericio** [marcuseckert/Squall#8]
On your [website](http://www.marcuseckert.com/squall/downloads/), we can download the release **1.13** but Squall is not available on GitHub and Cocoapods. Can you fix that please?

Thank you so much ☀️

**Comment by marcuseckert** [comment]
The versions there differ a bit but they should contain the same functionality. Are you missing sth?

**Comment by aymericio** [comment]
I updated an animation today and I got an error:

```
error Error Domain=com.marcuseckertAS.Squall.Error Code=7 "Unsupported file version.
File version: 0.000000
Minimum Supported Version: 1.005000.
Please update the Squall Extension." UserInfo={NSLocalizedDescription=Unsupported file version.
File version: 0.000000
Minimum Supported Version: 1.005000.
Please update the Squall Extension.}
```

**Comment by marcuseckert** [comment]
Looks more like a corrupt file. Can you send me the file?
